default_install_hook_types: [pre-commit, prepare-commit-msg]
repos:
  - repo: https://github.com/SethAngell/semantic-commit-formatter
    rev: v1.1.3
    hooks:
      - id: semantic_commit
        stages: [prepare-commit-msg]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.53.0
    hooks:
    -   id: eslint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
