name: 'Semantic Commit Changelog Generator'
description:
  'Given an array of semantic commits from commit lint, groups and generates a
  changelog in the markdown format.'
author: 'Seth Angell'

branding:
  icon: 'scissors'
  color: 'blue'

inputs:
  semantic_commits:
    description: 'An array of semantic commit messages'
    required: true
    default: '[]'

outputs:
  changelog:
    description: 'A markdown formatted changelog of your commits.'
  type:
    description: 'What kind of versioning action this should trigger: MAJOR, MINOR, or PATCH.'

runs:
  using: node20
  main: dist/index.js
