name: Lint Commit Messages
on: [pull_request]

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v5
        name: Parse Commits
        id: parse_commits
        with:
          failOnErrors: false
      - name: Generate Changelog
        id: changelog-generator
        uses: ./
        with:
          semantic_commits: ${{ toJSON(steps.parse_commits.outputs.results) }}
      - name: Print Results
        id: output
        run: echo "${{ steps.changelog-generator.outputs.changelog }}"
